apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-gslw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-edwh-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-gslw@sha256:5117b094eb8b809febf0e3951a14f9e6bcdbdb0821e6aa445cbd0cbf4dfb52f3
        name: my-python
        resources: {}
status: {}
